services:
  - type: web
    name: fastapi-messenger
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.9
